### ISSUE TITLE
No Connection Error

### ISSUE THREAD

**Issue by Adrian0350** [h3imdall/ftp-remote-edit#130]
I created a connection with sftp and yesterday it worked after a few tries changing the port.
However the same configuration for yesterday's connection does not work today and it does not display any kind of connection error. So credentials are good and connection should be (or was) established but the contents do not get displayed in the panel.

PS: Animation for connection (the arrow loop) has some CSS issues because it rotates imperfectly.

**Comment by cschindl** [comment]
Hi @Adrian0350 ,

I think this is the same mistake #129. Please wait until the next release. Then adjust your server settings. If the error should occur again (which I don't believe) we can reopen this post here. 

And you're right the CSS animation is not quite perfect. Unfortunately, this is because the icon used is not completely symmetrical. But I think we can live with this little inaccuracy ;)
