### ISSUE TITLE
Setting to allow access without entering master password

### ISSUE THREAD

**Issue by danallendotcom** [h3imdall/ftp-remote-edit#148]
The only system I use regularly that needs me to enter a password every time is ftp-remote in atom. It is annoying entering it every time I start Atom.  All my work is done on remote servers so I never start atom without typing my password.

Passwords in other systems are all entered automatically one way or another, once I enter them once.

So, I would like a way to avoid entering passwords every time atom starts.

**Comment by cschindl** [comment]
Hi @danallendotcom, 

your wish has already been suggested in #82. The input of the master password is part of the security concept. It is therefore not advisable to save the master password because it could be used by someone other to decrypt all access data.

The great advantage of Ftp-Remote-Edit is that all access data are securely encrypted and protected against access by others. Since the plugin is open-source, it is not possible to implement internal encryption like other software, because all information is readable by everyone.
