### ISSUE TITLE
Symlinks are not displayed

### ISSUE THREAD

**Issue by dev-studio** [h3imdall/ftp-remote-edit#159]
Please add symlinks to be visible when browsing folders. They may be in "blue" color...

**Comment by cschindl** [comment]
Hi @dev-studio,

Your wish has already been reported in #85. Symlinks are currently not supported because the (S)FTP protocol only reports that the entry is a symlink. Unfortunately, there is no indication whether this is a directory or a file. If you have an idea how to solve the problem, then we will gladly add the functionality for symlinks.
