### ISSUE TITLE
ftp-remote-edit doesn't show symbolic links in TreeView

### ISSUE THREAD

**Issue by morgana2313** [h3imdall/ftp-remote-edit#176]
And that's a pity...

**Comment by cschindl** [comment]
Hi @morgana2313 ,

Your wish has already been reported in #85. Symlinks are currently not supported because the (S)FTP protocol only reports that the entry is a symlink. Unfortunately, there is no indication whether this is a directory or a file. If you have an idea how to solve the problem, then we will gladly add the functionality for symlinks.

**Comment by LukeP1** [comment]
I also need to be able to see the symlinks, when the protocol reports the symlinks can commands not be run at this point to determine if it is a file or a full directory?
