### ISSUE TITLE
Support for TCP Keepalive

### ISSUE THREAD

**Issue by chikoi** [h3imdall/ftp-remote-edit#204]
The connection gets lost after a while of inactivity and it would be very helpful for us to set keepalives or at least hardcode a 10 seconds keepalive.

**Comment by JustForrest** [comment]
@chikoi is this the problem that causes my connection to become "stuck" if I leave Atom open and wake my computer after it's been asleep for a while?

**Comment by cschindl** [comment]
@JustForrest I think your pc loses its connection after waking up and connection become "stuck" is because of this #258 . The connection is terminated, but this is not detected. I have fixed the error. It is now checked if there is a timeout for the connection. In the next release everything should work again. Kepp alive is supported. For FTP connections a NOOP command is sent every 10 seconds to keep the connection up and SFTP also tries to keep the connection up.
