### ISSUE TITLE
A lot of work unable to be hooked due to separate Ftp-Remote-Edit Pane

### ISSUE THREAD

**Issue by joshupetersen** [h3imdall/ftp-remote-edit#210]
A number of packages reference the Project pane (such as things that add some right-click functionality for interfacing with files). An option to have the ftp-remote-edit connections as additional folder in the project pane instead of in their own pane might address these.

**Comment by cschindl** [comment]
Hi @joshupetersen ,

I'm afraid I don't understand your concern. The plugin provides the possibility to edit files directly on the server without having the files locally in a project. So why should you provide an option for the connections in the project pane?

**Comment by joshupetersen** [comment]
The reason is a fair number of packages hook into the project pane.

For example, say I'm using one of the git-diff oriented packages, and said package allows you to right-click a file in the project pane and view the diffs in a visually useful format. Being in a separate pane, the ftp-remote-edit pane doesn't get access to this additional right-click functionality, rendering many packages (such as my hypothetical git diff viewer) useless. If ftp-remote-edit could allow instead of opening in a new pane, alter the project pane by adding additional folders (not editing the files mind you, just editing the pane view & connections with associated) that might allow a number of functionalities to be retained.

**Comment by joshupetersen** [comment]
@cschindl 
The reason is a fair number of packages hook into the project pane.

For example, say I'm using one of the git-diff oriented packages, and said package allows you to right-click a file in the project pane and view the diffs in a visually useful format. Being in a separate pane, the ftp-remote-edit pane doesn't get access to this additional right-click functionality, rendering many packages (such as my hypothetical git diff viewer) useless. If ftp-remote-edit could allow instead of opening in a new pane, alter the project pane by adding additional folders (not editing the files mind you, just editing the pane view & connections with associated) that might allow a number of functionalities to be retained.

**Comment by cschindl** [comment]
Hi @joshupetersen ,

Mixing 2 plugins is not allowed by Atom unless the plugin has access points. An integration into the TreeView plugin, which creates the project pane, is unfortunately not possible. To work locally and to use all possibilities like the git diffs is not possible with this plugin because it was only developed for remote file editing. The best thing is to have a look at the plugin "remote-ftp". It synchronizes all (S)FTP files from the server with a local project. Here you work locally and always have to synchronize all files with the server, but you can use all plugins which have to access local files in the project directory.
