### ISSUE TITLE
unable to save setup (screen issue)

### ISSUE THREAD

**Issue by converge** [h3imdall/ftp-remote-edit#218]
hey guys,

I can't save my setup, the button is hidden.

![screen](https://i.imgur.com/5cq2IeG.png)

**Comment by cschindl** [comment]
Hi @converge ,

this looks like a display error. Most of the times this is due to badly adapted themes. This plugin is optimized for the Atom default themes (Atom Dark, Atom Light, One Dark, One Light). Please try if the standard theme works without errors. If this is the case, you, we together or the theme author can only try to modify the theme.
