### ISSUE TITLE
Settings window isnt usable

### ISSUE THREAD

**Issue by ZoomRidge** [h3imdall/ftp-remote-edit#221]
The setup panel for the package is condensed into a small box on the top of the page, unusable for setting anything up. Image attached: [https://imgur.com/a/sWMpM28](url)

**Comment by cschindl** [comment]
Hi @ZoomRidge,

this looks like a display error. Most of the times this is due to badly adapted themes. This plugin is optimized for the Atom default themes (Atom Dark, Atom Light, One Dark, One Light). Please try if the default theme works without errors. If this is the case, you, we together or the theme author can only try to modify the theme.

**Comment by cschindl** [comment]
@ZoomRidge Can I close this issue here?
