### ISSUE TITLE
Feature Request:  Connect/Disconnect

### ISSUE THREAD

**Issue by DiegoLpVn** [h3imdall/ftp-remote-edit#226]
Hi, 
I would like an option to be able to connect/disconnect whenever I wanted.

Thanks in advance :)

**Comment by cschindl** [comment]
Hi @DiegoLpVn,

to terminate the connection, it is only necessary to collapse the server node. The connection is automatically established when the node is expanded or every action is performed (download/upload). 
Since the connection is automatically re-established I don't know how useful it is to add a "connect/disconnect" function.
