### ISSUE TITLE
I can not see anything

### ISSUE THREAD

**Issue by Sharkelli** [h3imdall/ftp-remote-edit#231]
Why I can not see anything?
I can actually write and I can connect, but I never see anything of what I write.
![schermata 2018-12-02 alle 20 43 43](https://user-images.githubusercontent.com/45542498/49344178-15f7ca00-f674-11e8-8318-f5e4118aaa25.png)

**Comment by cschindl** [comment]
Hi @Sharkelli ,

this looks like a display error. Most of the times this is due to badly adapted themes or fonts. This plugin is optimized for the Atom default themes (Atom Dark, Atom Light, One Dark, One Light). Please try if the default theme works without errors. If this is the case, you, we together or the theme author can only try to modify the theme.

**Comment by cschindl** [comment]
Hi @Sharkelli,

did you try changing the theme? I'm closing this issue here now. If your problem still exists I can reopen it.
