### ISSUE TITLE
[Feature Request] Allow to reload opened file from context menu

### ISSUE THREAD

**Issue by Dallo71** [h3imdall/ftp-remote-edit#239]
When a file is changed outside Atom is not automatically refreshed but there is no option to make it by hand. The only option is to close all the file tabs and reopen...
It will be nice have a contextual menu entry to reload a file without close and reopen tabs

Thank you

**Comment by cschindl** [comment]
If files are changed locally, atom reloads them automatically. A reload button is therefore not necessary. If they are changed on the remote server, the changes are not reloaded by atom because no local files have been changed.

The solution could be to synchronize the files with the server. So you can add an option to reload a file in the context menu. You should then check which version is the most up-to-date (local or remote). If the local version is newer you can skip the next step. However, if the remote version is newer, the user must be notified and given a choice whether to download the newer remote version and replace his local version or to cancel. If he confirmed, the local version will be replaced and automatically reloaded into atom.

**Comment by th23x** [comment]
Would love to see this feature being added - to my understanding I would simply add a shortcut (key combination) and/or button to reload the file from the server.

**Comment by wacki4** [comment]
th23x - how would You like it to work - only reload, or see changes in file? By what, modify date compare, content? How to work when there will be a difference between files?

**Comment by th23x** [comment]
Hey wacki4, I would suggest to keep it very simple at first and just allow for a reload from server without any check for overwriting anything local - my basic usecase is eg a log file that I frequently would like to refresh from the server when coding...not even any need for displaying changes. Thanks for considering :-)

**Comment by wacki4** [comment]
So try to convice cschindl, your need is ready on #247 ;)

**Comment by ivokostov** [comment]
This will be very useful for reading .log file like a error_log

**Comment by cschindl** [comment]
Changes are now included in the new release ([0.15.0)](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.15.0).
