### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by webdezignx** [h3imdall/ftp-remote-edit#295]
It was working fine via ssh agent connection until yesterday, just stoped working by giving an error as "All configured authentication methods failed" on all saved servers. Tried removing them and reconfiguring, no luck.
No other 3rd party plugins are installed.

**Comment by cschindl** [comment]
Hi @webdezignx,

in order to help you we need more information. Which OS do you use? Have you updated your OS or SSH agent? Has there been an update on the server? Has an encryption procedure been exchanged on the server? Can you connect to the server with another program and the SSH agent? What kind of SSH private keys do you use? 

The error message is thrown by the sftp library if no matching authentication method can be found. We use the [ssh2-sftp-client](https://github.com/jyu213/ssh2-sftp-client) library. Have you checked here if other users might have the same problem?

**Comment by cschindl** [comment]
@webdezignx, 

I hope my answer could help you. Since I did not receive an answer from you, I close the issue here.

**Comment by webdezignx** [comment]
Applogies for the delay and thanks for your suggestions. However i was able to connect by different method. It was caused by IOS update.
