### ISSUE TITLE
"Find in project" function

### ISSUE THREAD

**Issue by LoYungSum** [h3imdall/ftp-remote-edit#329]
The above function is not working and will result in "No Results" while scanning 0 files. Can it be fixed?

**Comment by cschindl** [comment]
Hi @LoYungSum,

I'm a little confused. There is no "Find in Project" function. Do you mean the "Fuzzy File Finder"?

**Comment by LoYungSum** [comment]
The atom built-in function "Find in Project"

**Comment by cschindl** [comment]
Ahh, so this is the misunderstanding. This plugin works with the remote files and not with a local project. The "find in project" function can therefore not work. If you prefer to work with local projects that you want to synchronize with your FTP server, you can try the plugin "remote-ftp". This will mirror the local and remote files. But you only work with the local files in a local project, so you can use the function as well. Since our plugin was created for other purposes, we won't want to change anything on it.
