### ISSUE TITLE
500 Syntax error, command unrecognized since update

### ISSUE THREAD

**Issue by nicorank20** [h3imdall/ftp-remote-edit#331]
I updated to 0.17.3 and now get the 500 syntax error without a change to the server settings

**Comment by cschindl** [comment]
Hi @nicorank20 ,

i think that's the same problem as in this issue #328. Please check if you get a 500 error when listing a directory/server. If so, please post the debug protocol and a screenshot of the ftp log. I will close the issue here for now. If it's another problem, I can reopen the issue here.
