### ISSUE TITLE
Hotkey for toggling the tree

### ISSUE THREAD

**Issue by jordan-webdev** [h3imdall/ftp-remote-edit#37]
Maybe I'm missing it, but I can't seem to find any hotkey to hide/show the tree. It would be nice rather than having to go through the menu each time.

**Comment by miles-collier** [comment]
I added a hotkey and pulled, if @h3imdall likes the change it'll show up on next update.

I felt ctrl-space was easy to use and didn't seem used.

**Comment by cschindl** [comment]
We plan to change the plugin to support the Atom Editor's new design so that docks are used instead of panels. This would have the advantage that you can display the plugin as a tab next to the projects. In the footer should be displayed a link with which you can toggle the plugin. But the solution via a hotkey still seems to me a good idea.

**Comment by jordan-webdev** [comment]
Cool! I think some people will prefer the current design, as well, so perhaps it's best to have an option- one or the other. I think the tree-like design of the files is great and you should keep that :). It's so nice being able to see lots of files at once.

**Comment by h3imdall** [comment]
@miles-collier i merged your pull-request in the new version. 
You will be mentioned in the readme under the point special thanks.
