### ISSUE TITLE
configArray is not defined when using Pulsar

### ISSUE THREAD

**Issue by rheeqp** [h3imdall/ftp-remote-edit#446]
When using Pulsar version 1.101.0-beta, i got this error:

```
configArray is not defined
[Hide Stack Trace](https://github.com/h3imdall/ftp-remote-edit/issues/new#)
ReferenceError: configArray is not defined
    at Storage.load (storage.js:56:22)
    at ConfigurationView.close (configuration-view.js:765:13)
    at HTMLButtonElement.<anonymous> (configuration-view.js:80:12)
```

**Comment by brunoalbim** [comment]
I have the same problem.

I migrated from a notebook, from Windows to MAC, so I needed to install the atom to use the ftp-remote-edit pack, but I can't search for the packs using the atom.

so I downloaded the pulsar, but it gives the same error.

I saw that this error is only happening in Pulsar, because I downloaded the atom, even archived, and manually copied the files from ftp-remote-edit and added them to the "packages" folder of the atom, so I was able to use and connect via ftp.

however on Pulsar, it gives this same problem.

Do you have a compatibility prediction?

it would be really good.

**Comment by IggsGrey** [comment]
On line 56 of [this file](https://github.com/h3imdall/ftp-remote-edit/blob/master/lib/helper/storage.js) `configArray` was used without an initializer, neither was it ever initialized within the file. Hence the variable is clearly undefined. It's a bit weird why it only happens in pulsar and not in atom, however i suppose it could be due to a missing update in apm.

The problem now is, how do we get @h3imdall to solve it or merge a pull request?

**Comment by IggsGrey** [comment]
[This PR](https://github.com/h3imdall/ftp-remote-edit/pull/447) seems to have a fix

**Comment by Luishi5000** [comment]
In the meantime, how do we get that PR to work with Pulsar? I've downloaded the fork but don't know where the package files go on MacOS.

**Comment by rheeqp** [comment]
> [This PR](https://github.com/h3imdall/ftp-remote-edit/pull/447) seems to have a fix

**Comment by rheeqp** [comment]
https://github.com/h3imdall/ftp-remote-edit/issues/446#issuecomment-1425562126

I've used this PR, seems good

**Comment by IggsGrey** [comment]
@Luishi5000 and anyone else who might find this helpful.

To use [this PR](https://github.com/h3imdall/ftp-remote-edit/pull/447)

Just copy (and overwrite) the contents of the downloaded files from [the fork](https://github.com/xingkongwuhen/ftp-remote-edit/tree/Pulsar), to the package installation folder.

On my MacOS, it is located at /Users/[USERNAME]/.pulsar/packages/ftp-remote-edit
On Ubuntu, it is located at /usr/lib/pulsar/packages/ftp-remote-edit

**Comment by cschindl** [comment]
I have made the adjustments, merged into the master and am now trying to release a new version. Unfortunately it is not as easy as it was under atom. (https://github.com/orgs/pulsar-edit/discussions/91)

I hope the problem can be fixed quickly, so that you can download/install the new version in Pulsar again without any problems.

**Comment by rheeqp** [comment]
> I have made the adjustments, merged into the master and am now trying to release a new version. Unfortunately it is not as easy as it was under atom. (https://github.com/orgs/pulsar-edit/discussions/91)
> 
> I hope the problem can be fixed quickly, so that you can download/install the new version in Pulsar again without any problems.

thank you so much.

**Comment by cschindl** [comment]
I was now able to successfully update the package on the pulsar package registry. The package can now be easily updated from within pulsar and should be fully functional from version [v0.20.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.20.0).
