### ISSUE TITLE
Try to open ftp-remote-edit in Pulsar

### ISSUE THREAD

**Issue by DarthDensus** [h3imdall/ftp-remote-edit#449]
Expected behavoir: ftp-remote-edit should toggle an let me add server with sftp

Problem: ftp-remote-edit ends with an error after typing masterpassword
  
![image](https://user-images.githubusercontent.com/20629024/223719911-df4a3d36-8604-4081-8451-de8ff8de4863.png)

If i press of "View Issue" im landing on this case https://github.com/h3imdall/ftp-remote-edit/issues/44 but this is not resolving the issue.

Can someone pls fix the problem, since atom was sunsetting i cant run ftp-remote-edit and i love this package.

**Comment by topa-LE** [comment]
I also used the **ftp-remote-edit** package for many years. Since I also switched to Pulsar, I hoped it would work again. With Atom it didn't work anymore either.

Would be great if the developer could solve the above problem, think many want to use the package further.

Thanks for fixing the bug.
![img_151](https://user-images.githubusercontent.com/63888024/225105771-ccf53b20-f127-432e-b162-74ca747e063e.png)

**Comment by nocturnalguru** [comment]
Also receiving this error?
Any update on this?

**Comment by nocturnalguru** [comment]
I tried to copy the files from ~/.atom to ~/.pulsar but got the same issue.
got the same error.
I then tried to set it up from scratch (setup a server) and got the following error

configArray is not defined

configArray is not defined
[Hide Stack Trace](https://github.com/h3imdall/ftp-remote-edit/issues/449#)
ReferenceError: configArray is not defined
    at Storage.load (storage.js:56:22)
    at ftp-remote-edit.js:488:23

**Comment by topa-LE** [comment]
There is no need to copy anything from ./atom to Pulsar. Reinstall Pulsar completely and install the ftp-remote-edit extension on this system.

Create a new server and you get the above error messages.

The problem was also like this in the last build of Atom, so you need to contact the developer of the package.

**Comment by cschindl** [comment]
I have made the adjustments, merged into the master and am now trying to release a new version. Unfortunately it is not as easy as it was under atom. (https://github.com/orgs/pulsar-edit/discussions/91)

I hope the problem can be fixed quickly, so that you can download/install the new version in Pulsar again without any problems.

**Comment by cschindl** [comment]
I was now able to successfully update the package on the pulsar package registry. The package can now be easily updated from within pulsar and should be fully functional from version [v0.20.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.20.0).

**Comment by topa-LE** [comment]
Perfectly ;-)
![img_159](https://user-images.githubusercontent.com/63888024/226171602-42f55a77-57f8-43b7-bb86-4d0458873381.png)

**Comment by DarthDensus** [comment]
@cschindl Thank you so much, nice work :)
