### ISSUE TITLE
Image view doesn't work

### ISSUE THREAD

**Issue by AlekseyGur** [h3imdall/ftp-remote-edit#58]
Hi!

Atom has Image view package by default. But it doesn't work if I try to watch images from remote server via sftp. Please, could you fix it?

Best regards,
Alex.

**Comment by cschindl** [comment]
Hi @AlekseyGur,

can you please tell me which picture format did not work. I have tested it with JPG, PNG and GIF files and all worked fine.

**Comment by AlekseyGur** [comment]
Hm... can't catch the mistake. 

- With one of my server only .jpg doesn't work. But gif, png, ico works.
- With another server only ico works. And png, gif, jpg doesn't.
- Shared hosting - everything works. 

May be that's because of server properties. I don't understand the problem.
For example, two equal files: 

1. https://amwayforfuture.ru/android-chrome-192x192.png
2. http://mama-predprinimatel.ru/android-chrome-192x192.png

Two different servers. But I can open second file in atom.

**Comment by cschindl** [comment]
Hi @AlekseyGur, 

I found the error. Transfermode was changed from utf8 to binary mode. Changes are available in the next release.

**Comment by AlekseyGur** [comment]
You are the best! Your plugin makes atom a better version of Notepad++ for Linux :) I was seeking it for many years...

**Comment by cschindl** [comment]
Hi @AlekseyGur,

changes are now available in current release 0.11.11. Can you please confirm the the changes fixed the reported error.

**Comment by cnrmck** [comment]
@cschindl This is now broken for me. I'm not sure why, but I cannot open pngs when they are on a remote server. 

They are being downloaded to my local machine, and it seems that they are somehow being changed. The shasum is different between the two. 

<img width="857" alt="shasum" src="https://user-images.githubusercontent.com/22061955/45381840-b7b2d200-b5c3-11e8-8811-6bfddc2a5750.png">

It makes it so that I cannot open the downloaded image in either the atom editor nor with Mac's built in Preview. 

Could you please fix it? 

Also, if this belongs in its own issue I am happy to move it

**Comment by cnrmck** [comment]
@cschindl This is now broken for me. I'm not sure why, but I cannot open pngs when they are on a remote server. 

They are being downloaded to my local machine, and it seems that they are somehow being changed. The shasum is different between the two. 

<img width="826" alt="shasum" src="https://user-images.githubusercontent.com/22061955/45382107-871f6800-b5c4-11e8-93d3-e423e91973a0.png">

It makes it so that I cannot open the downloaded image in either the atom editor nor with Mac's built in Preview. 

Could you please fix it? 

Also, if this belongs in its own issue I am happy to move it

**Comment by cschindl** [comment]
Hi @cnrmck,

I'll check it in the next few days.

**Comment by cnrmck** [comment]
Thank you
