### ISSUE TITLE
Feature request : no password needed

### ISSUE THREAD

**Issue by inwardmovement** [h3imdall/ftp-remote-edit#82]
It would be great to allow that no password is needed for opening ftp tree each time we open an atom session.

**Comment by cschindl** [comment]
Hi @inwardmovement, 

the input of the master password is part of the security concept. It is therefore not advisable to save the master password because it could be used by someone other to decrypt all access data. 

The great advantage of Ftp-Remote-Edit is that all access data are securely encrypted and protected against access by others.

**Comment by wacki4** [comment]
I would like to reopen it.

What if we allow user for save without password (other field, with explanation of risk), and also allow not write down password in servers and possibility to write password down while connecting?

In place where i work we use our own password manager, where everything is up-to-date. Also, more secure - each password have it own key for each user, to decrypt password with key You need active session and many more data. 

Having something like it would allow me at work have our local servers - with password saved in, where no one can connect from outside the network, and also on one plugin connection to our clients server - where i would like to have to write password while connecting. I think it would be a great feature!

**Comment by marius311** [comment]
I'm confused what exactly is encrypted, and also why ftp-remote-edit needs an extra password compared to anything else? If I am logged into my laptop which has my SSH private keys for SSH'ing into various servers, I can open a terminal and SSH into these servers without needing a password. But if I open ftp-remote-edit and try to open those same servers, ftp-remote-edit wants an extra password. I don't see why this extra level of security is necessary, I have already logged into my user account on my laptop, so at that point I have access to everything already, no?

**Comment by cschindl** [comment]
Hi @marius311,

the master password is used to decrypt the entire configuration (including all servers). Without decrypting the plugin has no information about the server (host, keyfile etc.). This is historically due to the fact that the plugin was the first to support FTP connections with passwords.
