### ISSUE TITLE
Symlinks arent shown in tree view

### ISSUE THREAD

**Issue by JohnBruce** [h3imdall/ftp-remote-edit#85]
Maybe I'm just dumb and theres a setting for this somewhere, but ftp-remote-edit is not showing symlinks for me in its tree view.

To reproduce:

1.  add a symlink to the directory that you set as the 'Initial Directory' for a server you plan to connect to.
2.  Connect to that server
3.  See that the symlink you created is not listed

**Comment by cschindl** [comment]
Hello @JohnBruce,

symlinks are currently not supported because the (S)FTP protocol only reports that the entry is a symlink. Unfortunately, there is no indication whether this is a directory or a file. If you have an idea how to solve the problem, then we will gladly add the functionality for symlinks.
